SELECT * FROM Client;
SELECT * FROM Pizza;
SELECT * FROM Ingredient;
SELECT * FROM Vehicule;
SELECT * FROM Livraison;
SELECT * FROM Composition;
SELECT * FROM Livreur;
SELECT * FROM Commande_Pizza;
SELECT * FROM Taille;